development:
  adapter: postgresql
  database: fit_tracker_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite
  host: localhost
  pool: 5
  timeout: 5000

production:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  database: fit_tracker_production
  host: localhost
  pool: 5
  timeout: 5000